from __future__ import annotations

import asyncio
import json
import logging
import time
from hashlib import sha256
from functools import lru_cache
from typing import Any

from openai import AsyncOpenAI, RateLimitError

from app.core.config import get_settings

logger = logging.getLogger(__name__)

# Global request throttle for free tier rate limiting
# Free tier: 3 requests per minute = 1 request per 20 seconds
_request_lock = asyncio.Lock()
_last_request_time = 0.0
_min_request_interval_s = 20.0  # Conservative: 3 req/min


class LLMError(RuntimeError):
    pass


class MockLLMClient:
    """Mock LLM client for development/testing when no valid API key is available."""
    
    async def generate_structured(self, *, system_prompt: str, user_prompt: str, json_schema: dict[str, Any], ) -> dict[str, Any]:
        """
        Return deterministic mock responses based on the prompt type.
        """
        logger.info("Using mock LLM client for development")
        
        # Extract topic from user prompt (simple parsing)
        topic = "Unknown"
        if "Topic:" in user_prompt:
            topic_line = user_prompt.split("Topic:")[1].split("\n")[0].strip()
            topic = topic_line
        
        # Return mock responses based on prompt type
        if "flashcards" in system_prompt.lower():
            return {
                "cards": [
                    {"question": f"What is the main use of {topic}?", "answer": "For actions completed in the past."},
                    {"question": f"How is {topic} formed?", "answer": "With auxiliary verb + past participle."},
                    {"question": f"When do we use {topic}?", "answer": "For specific, completed actions."},
                    {"question": f"Example of {topic}", "answer": "I have eaten (Ho mangiato)."},
                    {"question": f"Difference between {topic} and imperfect?", "answer": f"{topic} for completed actions, imperfect for ongoing/habitual."},
                ]
            }
        elif "multiple-choice" in system_prompt.lower() or "quizzes" in system_prompt.lower():
            return {
                "questions": [
                    {
                        "question": f"What is {topic} used for?",
                        "options": ["Future actions", "Completed actions", "Hypothetical situations", "Commands"],
                        "correct_index": 1,
                        "explanation": f"{topic} is used for actions that are completed in the past.",
                    }
                ]
            }
        elif "explain concepts" in system_prompt.lower():
            return {
                "summary": f"{topic} is a grammatical tense used to describe completed actions.",
                "key_points": [
                    f"{topic} describes finished actions",
                    "It's commonly used in conversation",
                    "Formed with auxiliary + past participle",
                    "Has specific time references"
                ],
                "analogy": "Like taking a photo of a completed action - the action is finished and captured.",
            }
        else:
            # Default response
            return {
                "response": f"This is a mock response for {topic}. In production, this would be generated by OpenAI.",
                "note": "Set a valid OPENAI_API_KEY in .env file for real AI responses."
            }


class LLMClient:
    def __init__(self, api_key: str, model: str, timeout_s: int, rate_limit_min_interval_s: float = 20.0, rate_limit_max_retries: int = 5) -> None:
        # Disable SDK retries - we handle retries ourselves
        self._client = AsyncOpenAI(api_key=api_key, timeout=timeout_s, max_retries=0)
        self._model = model
        self._cache: dict[str, tuple[float, dict[str, Any]]] = {}
        self._cache_ttl_s = 300.0
        self._cache_max_items = 128
        self._mock_fallback = MockLLMClient()
        # Retry configuration for rate limits
        self._max_retries = rate_limit_max_retries
        self._initial_retry_delay_s = 2.0  # Start with 2 seconds
        self._min_request_interval_s = rate_limit_min_interval_s

    def _cache_get(self, key: str) -> dict[str, Any] | None:
        now = time.time()
        hit = self._cache.get(key)
        if not hit:
            return None
        expires_at, payload = hit
        if expires_at < now:
            self._cache.pop(key, None)
            return None
        return payload

    def _cache_set(self, key: str, payload: dict[str, Any]) -> None:
        now = time.time()
        if len(self._cache) >= self._cache_max_items:
            # Drop oldest entry (simple, deterministic).
            oldest_key = min(self._cache.items(), key=lambda kv: kv[1][0])[0]
            self._cache.pop(oldest_key, None)
        self._cache[key] = (now + self._cache_ttl_s, payload)

    async def generate_structured(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        json_schema: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Enforces structured JSON output using OpenAI chat.completions with JSON schema.
        Implements request throttling for free tier rate limits and exponential backoff retry.
        Falls back to mock client if API fails or quota is exhausted.
        """
        global _last_request_time
        
        cache_key = sha256(
            (self._model + "\n" + system_prompt + "\n" + user_prompt + "\n" + json.dumps(json_schema, sort_keys=True)).encode(
                "utf-8"
            )
        ).hexdigest()
        cached = self._cache_get(cache_key)
        if cached is not None:
            logger.debug("Cache hit for LLM request", extra={"cache_key": cache_key[:8]})
            return cached

        # Throttle requests to respect free tier rate limits
        async with _request_lock:
            now = time.time()
            time_since_last = now - _last_request_time
            if time_since_last < self._min_request_interval_s:
                wait_time = self._min_request_interval_s - time_since_last
                logger.debug(f"Rate limit throttle: waiting {wait_time:.1f}s", extra={"wait_time_s": wait_time})
                await asyncio.sleep(wait_time)
            _last_request_time = time.time()

        # Retry loop with exponential backoff
        for attempt in range(self._max_retries):
            try:
                resp = await self._client.chat.completions.create(
                    model=self._model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    response_format={
                        "type": "json_schema",
                        "json_schema": {
                            "name": "study_helper_output",
                            "schema": json_schema,
                            "strict": True,
                        },
                    },
                )
                
                # Extract content from the response
                if not resp.choices or len(resp.choices) == 0:
                    raise LLMError("LLM response contained no choices")
                
                text = resp.choices[0].message.content
                if not text or not isinstance(text, str):
                    raise LLMError("LLM response contained no content")

                try:
                    parsed = json.loads(text)
                except Exception as e:  # noqa: BLE001 (boundary)
                    logger.warning("Failed to parse JSON from LLM", extra={"content": text})
                    raise LLMError("LLM returned invalid JSON") from e

                if not isinstance(parsed, dict):
                    raise LLMError("LLM JSON output must be an object")
                
                self._cache_set(cache_key, parsed)
                logger.debug("LLM request successful", extra={"attempt": attempt + 1})
                return parsed
                
            except RateLimitError as e:
                error_text = str(e)
                
                # Check for insufficient_quota - fall back immediately without retrying
                if "insufficient_quota" in error_text.lower():
                    logger.warning("OpenAI quota exhausted, falling back to mock client immediately", extra={"error": error_text})
                    result = await self._mock_fallback.generate_structured(
                        system_prompt=system_prompt,
                        user_prompt=user_prompt,
                        json_schema=json_schema,
                    )
                    self._cache_set(cache_key, result)
                    return result
                
                # For rate limits (429), retry with exponential backoff
                if attempt < self._max_retries - 1:
                    retry_delay = self._initial_retry_delay_s * (2 ** attempt)
                    logger.warning(
                        f"OpenAI rate limited (429). Retrying in {retry_delay:.1f}s (attempt {attempt + 1}/{self._max_retries})",
                        extra={"attempt": attempt + 1, "max_retries": self._max_retries, "retry_delay_s": retry_delay, "error": error_text}
                    )
                    await asyncio.sleep(retry_delay)
                    continue
                else:
                    # Max retries exceeded, fall back to mock
                    logger.warning(
                        f"OpenAI rate limit persisted after {self._max_retries} retries, falling back to mock client",
                        extra={"max_retries": self._max_retries, "error": error_text}
                    )
                    result = await self._mock_fallback.generate_structured(
                        system_prompt=system_prompt,
                        user_prompt=user_prompt,
                        json_schema=json_schema,
                    )
                    self._cache_set(cache_key, result)
                    return result
                    
            except Exception as e:  # noqa: BLE001 (boundary)
                logger.error(f"LLM client error: {str(e)}", extra={"attempt": attempt + 1, "error_type": type(e).__name__})
                # Fall back to mock on any other error
                result = await self._mock_fallback.generate_structured(
                    system_prompt=system_prompt,
                    user_prompt=user_prompt,
                    json_schema=json_schema,
                )
                self._cache_set(cache_key, result)
                return result
        
        # Should not reach here, but just in case
        logger.error("LLM client exhausted all retries without success")
        result = await self._mock_fallback.generate_structured(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            json_schema=json_schema,
        )
        self._cache_set(cache_key, result)
        return result


@lru_cache(maxsize=1)
def get_llm() -> LLMClient | MockLLMClient:
    settings = get_settings()
    
    # If USE_MOCK_LLM is enabled, skip OpenAI entirely
    if settings.use_mock_llm:
        logger.info("USE_MOCK_LLM is enabled, using mock LLM client")
        return MockLLMClient()
    
    # Check if we have a valid-looking API key
    # OpenAI API keys typically start with 'sk-' and are at least 20 chars
    has_valid_key = (
        settings.openai_api_key and 
        len(settings.openai_api_key) > 20 and 
        settings.openai_api_key.startswith('sk-')
    )
    
    if not has_valid_key:
        logger.warning(
            "No valid OpenAI API key found. Using mock LLM client for development. "
            "Set a valid OPENAI_API_KEY in .env file for real AI responses, or set USE_MOCK_LLM=true to skip this warning."
        )
        return MockLLMClient()
    
    return LLMClient(
        api_key=settings.openai_api_key,
        model=settings.openai_model,
        timeout_s=settings.openai_timeout_s,
        rate_limit_min_interval_s=settings.rate_limit_min_interval_s,
        rate_limit_max_retries=settings.rate_limit_max_retries,
    )
