from __future__ import annotations

import json
import logging
import time
from hashlib import sha256
from functools import lru_cache
from typing import Any

from openai import AsyncOpenAI
from tenacity import AsyncRetrying, RetryError, stop_after_attempt, wait_exponential_jitter

from app.core.config import get_settings

logger = logging.getLogger(__name__)


class LLMError(RuntimeError):
    pass


class MockLLMClient:
    """Mock LLM client for development/testing when no valid API key is available."""
    
    async def generate_structured(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        json_schema: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Return deterministic mock responses based on the prompt type.
        """
        logger.info("Using mock LLM client for development")
        
        # Extract topic from user prompt (simple parsing)
        topic = "Unknown"
        if "Topic:" in user_prompt:
            topic_line = user_prompt.split("Topic:")[1].split("\n")[0].strip()
            topic = topic_line
        
        # Return mock responses based on prompt type
        if "flashcards" in system_prompt.lower():
            return {
                "cards": [
                    {"question": f"What is the main use of {topic}?", "answer": "For actions completed in the past."},
                    {"question": f"How is {topic} formed?", "answer": "With auxiliary verb + past participle."},
                    {"question": f"When do we use {topic}?", "answer": "For specific, completed actions."},
                    {"question": f"Example of {topic}", "answer": "I have eaten (Ho mangiato)."},
                    {"question": f"Difference between {topic} and imperfect?", "answer": f"{topic} for completed actions, imperfect for ongoing/habitual."},
                ]
            }
        elif "multiple-choice" in system_prompt.lower() or "quizzes" in system_prompt.lower():
            return {
                "questions": [
                    {
                        "question": f"What is {topic} used for?",
                        "options": ["Future actions", "Completed actions", "Hypothetical situations", "Commands"],
                        "correct_index": 1,
                        "explanation": f"{topic} is used for actions that are completed in the past.",
                    }
                ]
            }
        elif "explain concepts" in system_prompt.lower():
            return {
                "summary": f"{topic} is a grammatical tense used to describe completed actions.",
                "key_points": [
                    f"{topic} describes finished actions",
                    "It's commonly used in conversation",
                    "Formed with auxiliary + past participle",
                    "Has specific time references"
                ],
                "analogy": "Like taking a photo of a completed action - the action is finished and captured.",
            }
        else:
            # Default response
            return {
                "response": f"This is a mock response for {topic}. In production, this would be generated by OpenAI.",
                "note": "Set a valid OPENAI_API_KEY in .env file for real AI responses."
            }


class LLMClient:
    def __init__(self, api_key: str, model: str, timeout_s: int, max_retries: int) -> None:
        self._client = AsyncOpenAI(api_key=api_key, timeout=timeout_s)
        self._model = model
        self._max_retries = max_retries
        self._cache: dict[str, tuple[float, dict[str, Any]]] = {}
        self._cache_ttl_s = 300.0
        self._cache_max_items = 128

    def _cache_get(self, key: str) -> dict[str, Any] | None:
        now = time.time()
        hit = self._cache.get(key)
        if not hit:
            return None
        expires_at, payload = hit
        if expires_at < now:
            self._cache.pop(key, None)
            return None
        return payload

    def _cache_set(self, key: str, payload: dict[str, Any]) -> None:
        now = time.time()
        if len(self._cache) >= self._cache_max_items:
            # Drop oldest entry (simple, deterministic).
            oldest_key = min(self._cache.items(), key=lambda kv: kv[1][0])[0]
            self._cache.pop(oldest_key, None)
        self._cache[key] = (now + self._cache_ttl_s, payload)

    async def generate_structured(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        json_schema: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Enforces structured JSON output using OpenAI chat.completions with JSON schema.
        Raises LLMError if the model output cannot be parsed or validated by the API.
        """
        cache_key = sha256(
            (self._model + "\n" + system_prompt + "\n" + user_prompt + "\n" + json.dumps(json_schema, sort_keys=True)).encode(
                "utf-8"
            )
        ).hexdigest()
        cached = self._cache_get(cache_key)
        if cached is not None:
            return cached

        try:
            async for attempt in AsyncRetrying(
                wait=wait_exponential_jitter(initial=1, max=8),
                stop=stop_after_attempt(self._max_retries),
                reraise=True,
            ):
                with attempt:
                    resp = await self._client.chat.completions.create(
                        model=self._model,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                        response_format={
                            "type": "json_schema",
                            "json_schema": {
                                "name": "study_helper_output",
                                "schema": json_schema,
                                "strict": True,
                            },
                        },
                    )
        except RetryError as e:
            raise LLMError("LLM request failed after retries") from e
        except Exception as e:  # noqa: BLE001 (boundary)
            raise LLMError("LLM request failed") from e

        # Extract content from the new response format
        if not resp.choices or len(resp.choices) == 0:
            raise LLMError("LLM response contained no choices")
        
        text = resp.choices[0].message.content
        if not text or not isinstance(text, str):
            raise LLMError("LLM response contained no content")

        try:
            parsed = json.loads(text)
        except Exception as e:  # noqa: BLE001 (boundary)
            logger.warning("Failed to parse JSON from LLM", extra={"content": text})
            raise LLMError("LLM returned invalid JSON") from e

        if not isinstance(parsed, dict):
            raise LLMError("LLM JSON output must be an object")
        self._cache_set(cache_key, parsed)
        return parsed


@lru_cache(maxsize=1)
def get_llm() -> LLMClient | MockLLMClient:
    settings = get_settings()
    
    # Check if we have a valid-looking API key
    # OpenAI API keys typically start with 'sk-' and are at least 20 chars
    has_valid_key = (
        settings.openai_api_key and 
        len(settings.openai_api_key) > 20 and 
        settings.openai_api_key.startswith('sk-')
    )
    
    if not has_valid_key:
        logger.warning(
            "No valid OpenAI API key found. Using mock LLM client for development. "
            "Set a valid OPENAI_API_KEY in .env file for real AI responses."
        )
        return MockLLMClient()
    
    return LLMClient(
        api_key=settings.openai_api_key,
        model=settings.openai_model,
        timeout_s=settings.openai_timeout_s,
        max_retries=settings.openai_max_retries,
    )
